# Central configuration file for the "NewDoc" Sage Documentation
title: Sage Mathematical Software Documentation
version: 0.0.1

remapping:
    test: { notsage : sage, alsothis: sage }

google_analytics: UA-66100-13