# Central configuration file for the "NewDoc" Sage Documentation
title: Sage Mathematical Software Documentation
version: 0.0.1

modules:
    - sage
    - sage_plotting
    - python
    - test

remapping:
    - test: { notsage : sage, alsothis: sage }

framework:
    directory: framework
